
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  latest_version: 84

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [82, 83, 84]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            manudonihubcoreai/composer:${{ matrix.php_version }}
            ${{ matrix.php_version == env.latest_version && 'manudonihubcoreai/composer:latest' || '' }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}